global sFLD sNF
sFLD = {'beta','se','p','z','isa','pc','pca','cr'};
% Parameter fields to read as numbers. 
% Declared here because forgetting to write a new parameter
% to parameters.out.tsv is a bug easy to introduce, tricky to debug
sNF = {...
'n_show',...
'dsh',...
'decorr_lambda','correlation_missing',...
'snp',...
'significant','suggestive',...
'n_permutation',...
'crscale','samplesize'...
};